### ISSUE TITLE
FAMOS TODO

### ISSUE THREAD

**Issue by k00ni** [AKSW/leds-asp-f-ontologies#1]
- Create small script to convert FAMOS export to building ontology in RDF

**Comment by fkoestner** [comment]
I created an ontology that adopts to the famos data structure by using terms from buildling ontology. The work on the script for converting the data to rdf has started.

**Comment by fkoestner** [comment]
the script works. It's missing two features. 
- units and measurements - because unit ontology is currently wip
- vertical connected rooms (strairways, elevators) - because no matching algorithm for rooms on different floors was found

**Comment by fkoestner** [comment]
script now adds values with corresponding usage of measuements-and-units ontology.

**Comment by fkoestner** [comment]
scribt is capable of finding and connect some rooms that are real world rooms. If the rooms are found depends on their namescheme. There are known name pattern exceptions that the script does not handle. I wasn't eveb able to find the connection myself. There are most likely more pattern not yet dound because the example export does not contain them.
For now the script is complete.

**Comment by k00ni** [comment]
Whats the status here?

**Comment by fkoestner** [comment]
There aren't any changes.  I didn't have the time for a full database wide pattern search. The main problem on this issue is the missing constance in the name patterns and the resulting exceptions. This problem may be solved best with the database creators. This issue could be closed, it just don't feels right.
